### PR TITLE
Add Mega-Newton unit to Structural environment

### PR DESCRIPTION
**Pull request by ccaprani**
For the bridge engineers out there...

### CODE REVIEW

**Review by connorferster — APPROVED** [review]

**Review by jukti3742 — COMMENTED** [review]
Hi. I would like to bring it to your notice that 'structural environment' in v2.6.0 is showing an error after @connorferster accepted the following change. 
`"MN": {
        "Dimension": [1,1,-2,0,0,0,0],
        "Value": 1_000_000},`
I think the value should be 1e6 instead of 1_000_000. Let me know if I am right.

**Comment by connorferster** [comment]
Agreed. Patched in v.2.6.1

**Comment by ccaprani** [comment]
That's really strange. Underscores in numeric literals was [PEP 515](https://peps.python.org/pep-0515/) and introduced in python 3.6.

**Comment by connorferster** [comment]
I think it has to do with the environment file being a .json and not a .py file.

**Pull request merged**
