### PR TITLE
Move .json files to share folder

### PR DESCRIPTION
**Pull request by JimZwartveld**
Hi Connor,

I went ahead and made some changes;
- Moved all .json files to environment/share/forallpeople
- Updated si_environment.py and environment.py (is one of them outdated? why do you need two?) to find the new .json path.

I tested loading the default environment using an installed pip package with these updates, and that all worked fine. 

Kind regards, 
Jim

### CODE REVIEW

**Comment by JimZwartveld** [comment]
@connorferster can you have a look at this merge request?

**Comment by connorferster** [comment]
Hi @JimZwartveld,

Thank you for the nudge! I like the general idea but I don't know if creating the `/share` directory outside of the package directory is the way to go. Even though there is still a `setup.py` file, I am trying to get away from it entirely and stick with `pyproject.toml`. The `flit` build tool does not have support for data files (like you have created in the `setup.py` file). While I was doing some internet searching about this, I found out that support for data files in `setup.py` is [now also deprecated](https://setuptools.readthedocs.io/en/latest/references/keywords.html?highlight=data_files):

image

Could you describe your use case for me? I agree that having the directory deep in `site-packages` is a pain in the butt. It would be nicer to have a closer-to-user location but, as a Python package, it makes sense to keep them with the package as far as package distribution is concerned. Let me know your thoughts on this.

**Comment by JimZwartveld** [comment]
Thanks for your quick reply @connorferster! I see what you mean, the advice is indeed to keep all project related files within your own repository. 

We're building a web interface shell around in-house developed software (with an outdated user interface). The user provides data in a table-like format, where they can provide units in each cell. In the back-end, the input string is parsed to a Physical class and converted to units that the in-house software demands. I wanted control over the units environment, and figured out that forallpeople only recognizes .json files that are stored in the forallpeople repository. Since we're creating a python package ourselves, our .json environment is stored in our own repository. 

An alternative solution that I can think of is that the user can provide a path to an environment, rather than only the name of one of the existing environments.

```
import forallpeople as si
si.environment("path_to_environment")
```

In this way, I can make sure that my python package registers the right .json environment that is stored outside forallpeople.
What is your idea about this?

**Comment by connorferster** [comment]
I love it. Providing a path makes so much sense and can work well with the existing approach.

I am also building an in-house design application at work that will depend on forallpeople. I realized a couple of weeks ago that forallpeople was slowing down the software when manipulating 100,000s of objects. I made some significant performance enhancements recently and it is now running in a fraction of the previous time, which I am really happy about. Hopefully it works well for your application, also!

I have been starting to use streamlit for application design now that they can handle session state well. Have you tried it? So fast to make a thing!

**Comment by JimZwartveld** [comment]
Up to now I haven't encountered any problems whatsoever! Very nice that you've been able to speed everything up. 

You don't have a string parser included at the moment right? We're still reviewing ours, maybe we can add it to forallpeople so that other people can create Physical instances from a string as well. Any input from text boxes or tables can then simply be converted to Physical.

Haven't used streamlit, had to google it but it looks user friendly! We've been using dash/plotly for this project, might use streamlit when I see an application for it. Thanks for the tip!

**Review by connorferster — APPROVED** [review]
That looks good, Jim!

**Pull request merged**
